    HardcodedDefaultEntry{
        0u, "Showcase foundation",
        {0.0f, 0.139999986f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {30.0f, 0.280000001f, 11.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        1u, "Showcase floor",
        {0.0f, 0.340000004f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {29.2999992f, 0.119999997f, 10.3000002f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        2u, "Showcase expanded rear wall",
        {0.0f, 3.3499999f, -19.4599991f},
        {0.0f, 0.0f, 0.0f},
        {30.3999996f, 6.69999981f, 0.340000004f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        3u, "Showcase rear wall cap",
        {0.0f, 6.76000023f, -19.3999996f},
        {0.0f, 0.0f, 0.0f},
        {30.7000008f, 0.119999997f, 0.219999999f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        4u, "Showcase west wall",
        {-15.0f, 3.25f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {0.300000012f, 6.5f, 11.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        5u, "Showcase east wall",
        {15.0f, 3.25f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {0.300000012f, 6.5f, 11.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        6u, "Showcase room divider",
        {-7.5f, 2.95000005f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {0.180000007f, 5.80000019f, 10.3999996f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        7u, "Showcase room divider",
        {0.0f, 2.95000005f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {0.180000007f, 5.80000019f, 10.3999996f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        8u, "Showcase room divider",
        {7.5f, 2.95000005f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {0.180000007f, 5.80000019f, 10.3999996f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        9u, "Showcase front header",
        {0.0f, 6.17999983f, -8.57999992f},
        {0.0f, 0.0f, 0.0f},
        {30.2000008f, 0.280000001f, 0.300000012f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        10u, "Showcase rear roof",
        {0.0f, 6.42000008f, -16.6000004f},
        {0.0f, 0.0f, 0.0f},
        {30.3999996f, 0.25f, 5.5f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        11u, "Showcase glass canopy",
        {-11.25f, 6.36000013f, -11.3500004f},
        {0.0f, 0.0f, 0.0f},
        {7.0999999f, 0.100000001f, 5.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        12u, "Showcase glass canopy",
        {-3.75f, 6.36000013f, -11.3500004f},
        {0.0f, 0.0f, 0.0f},
        {7.0999999f, 0.100000001f, 5.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        13u, "Showcase glass canopy",
        {3.75f, 6.36000013f, -11.3500004f},
        {0.0f, 0.0f, 0.0f},
        {7.0999999f, 0.100000001f, 5.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        14u, "Showcase glass canopy",
        {11.25f, 6.36000013f, -11.3500004f},
        {0.0f, 0.0f, 0.0f},
        {7.0999999f, 0.100000001f, 5.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        15u, "Room light ceiling mount",
        {-11.1999998f, 5.82000017f, -12.1999998f},
        {0.0f, 0.0f, 0.0f},
        {0.319999993f, 0.180000007f, 0.319999993f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        16u, "Room light cable",
        {-11.1999998f, 4.88000011f, -12.1999998f},
        {0.0f, 0.0f, 0.0f},
        {0.0350000001f, 1.70000005f, 0.0350000001f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        17u, "Room point-light glass globe",
        {-11.1999998f, 4.0f, -12.1999998f},
        {0.0f, 0.0f, 0.0f},
        {0.340000004f, 0.340000004f, 0.340000004f},
        {1.0f, 1.0f, 1.0f},
        "UV sphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        18u, "Room point-light emissive bulb",
        {-11.1999998f, 4.0f, -12.1999998f},
        {0.0f, 0.0f, 0.0f},
        {0.129999995f, 0.129999995f, 0.129999995f},
        {1.0f, 1.0f, 1.0f},
        "Icosphere", true, false,
        {7.0f, 1.53999996f, 0.0f, 0.0f},
        "Point light 1"
    },
    HardcodedDefaultEntry{
        19u, "Room light ceiling mount",
        {-3.70000005f, 5.92000008f, -12.0f},
        {0.0f, 0.0f, 0.0f},
        {0.319999993f, 0.180000007f, 0.319999993f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        20u, "Room light cable",
        {-3.70000005f, 4.98000002f, -12.0f},
        {0.0f, 0.0f, 0.0f},
        {0.0350000001f, 1.70000005f, 0.0350000001f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        21u, "Room point-light glass globe",
        {-3.70000005f, 4.0999999f, -12.0f},
        {0.0f, 0.0f, 0.0f},
        {0.340000004f, 0.340000004f, 0.340000004f},
        {1.0f, 1.0f, 1.0f},
        "UV sphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        22u, "Room point-light emissive bulb",
        {-3.70000005f, 4.0999999f, -12.0f},
        {0.0f, 0.0f, 0.0f},
        {0.129999995f, 0.129999995f, 0.310000002f},
        {0.949999988f, 1.0f, 1.0f},
        "Icosphere", true, false,
        {8.70693207f, 1.45200002f, 0.0f, 0.0f},
        "Point light 2"
    },
    HardcodedDefaultEntry{
        23u, "Room light ceiling mount",
        {10.8000002f, 5.82000017f, -12.1000004f},
        {0.0f, 0.0f, 0.0f},
        {0.319999993f, 0.180000007f, 0.319999993f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        24u, "Room light cable",
        {10.8000002f, 4.88000011f, -12.1000004f},
        {0.0f, 0.0f, 0.0f},
        {0.0350000001f, 1.70000005f, 0.0350000001f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        25u, "Room point-light glass globe",
        {10.8000002f, 4.0f, -12.1000004f},
        {0.0f, 0.0f, 0.0f},
        {0.340000004f, 0.340000004f, 0.340000004f},
        {1.0f, 1.0f, 1.0f},
        "UV sphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        26u, "Room point-light emissive bulb",
        {10.8000002f, 4.0f, -12.1000004f},
        {0.0f, 0.0f, 0.0f},
        {0.129999995f, 0.129999995f, 0.129999995f},
        {1.0f, 1.0f, 1.0f},
        "Icosphere", true, false,
        {7.5f, 1.88999987f, 0.0f, 0.0f},
        "Point light 3"
    },
    HardcodedDefaultEntry{
        27u, "Display pedestal",
        {-11.25f, 0.779999971f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {4.80000019f, 0.779999971f, 3.4000001f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        28u, "Brushed aluminum pedestal trim",
        {-11.25f, 1.19339991f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {4.9920001f, 0.0599999987f, 3.53600001f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        29u, "Brushed aluminum torus",
        {-11.25f, 2.04999995f, -14.0f},
        {0.0f, 3241.00586f, 0.0f},
        {1.67867875f, 0.900736332f, 0.835908711f},
        {1.0f, 1.0f, 1.0f},
        "Torus", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        30u, "Automotive clearcoat sphere",
        {-12.8622017f, 1.75f, -12.8774261f},
        {0.0f, 2102.74438f, 0.0f},
        {1.17999995f, 1.17999995f, 1.17999995f},
        {1.0f, 1.0f, 1.0f},
        "UV sphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        31u, "Rubber roughness reference",
        {-9.63613129f, 1.43793297f, -12.9774246f},
        {0.0f, 0.0f, 0.0f},
        {0.835903227f, 0.581305265f, 0.857991397f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        32u, "Metal shadow occluder fin",
        {-12.75f, 2.0999999f, -16.75f},
        {0.0f, 0.314159274f, 0.0f},
        {0.239999995f, 3.25f, 1.04999995f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        33u, "Metal shadow occluder fin",
        {-11.25f, 2.0999999f, -16.75f},
        {0.0f, 0.314159274f, 0.0f},
        {0.239999995f, 3.25f, 1.04999995f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        34u, "Metal shadow occluder fin",
        {-9.75f, 2.0999999f, -16.75f},
        {0.0f, 0.314159274f, 0.0f},
        {0.239999995f, 3.25f, 1.04999995f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        35u, "Display pedestal",
        {-3.75f, 0.720000029f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {5.0f, 0.660000026f, 3.5f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        36u, "Brushed aluminum pedestal trim",
        {-3.75f, 1.06980002f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {5.19999981f, 0.0599999987f, 3.63999987f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        37u, "Brick wall structure",
        {-3.75f, 2.54999995f, -18.9599991f},
        {0.0f, 0.0f, 0.0f},
        {3.29999995f, 2.25f, 0.159999996f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        38u, "Brick parallax receiver",
        {-3.75f, 3.20153618f, -18.7849998f},
        {1.57079637f, 0.0f, 0.0f},
        {3.60304976f, 0.0199999996f, 2.80237842f},
        {1.0f, 1.0f, 1.0f},
        "Plane", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        39u, "Wall cap",
        {-3.75f, 4.88000011f, -18.9599991f},
        {0.0f, 0.0f, 0.0f},
        {3.43199992f, 0.0799999982f, 0.219999999f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        40u, "Parallax depth comparison panel",
        {-3.75f, 1.04999995f, -13.6000004f},
        {1.57079637f, 0.0f, 0.0f},
        {1.95000005f, 1.0f, 1.54999995f},
        {1.0f, 1.0f, 1.0f},
        "Plane", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        41u, "Projected light occluder A",
        {-5.3499999f, 2.1500001f, -12.0f},
        {0.0f, 0.0f, 0.0f},
        {0.449999988f, 3.5f, 0.449999988f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        42u, "Projected light occluder B",
        {-2.1500001f, 1.64999998f, -12.5f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 2.5f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        43u, "RTT screen top frame",
        {2.1500001f, 2.96000004f, -18.914999f},
        {0.0f, 0.0f, 0.0f},
        {3.08999991f, 0.159999996f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        44u, "RTT screen bottom frame",
        {2.1500001f, 1.19999993f, -18.914999f},
        {0.0f, 0.0f, 0.0f},
        {3.08999991f, 0.159999996f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        45u, "RTT screen left frame",
        {0.695000112f, 2.07999992f, -18.914999f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 1.75999999f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        46u, "RTT screen right frame",
        {3.60500002f, 2.07999992f, -18.914999f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 1.75999999f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        47u, "RTT screen top frame",
        {5.30000019f, 2.96000004f, -18.914999f},
        {0.0f, 0.0f, 0.0f},
        {3.08999991f, 0.159999996f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        48u, "RTT screen bottom frame",
        {5.30000019f, 1.19999993f, -18.914999f},
        {0.0f, 0.0f, 0.0f},
        {3.08999991f, 0.159999996f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        49u, "RTT screen left frame",
        {3.84500027f, 2.07999992f, -18.914999f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 1.75999999f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        50u, "RTT screen right frame",
        {6.75500011f, 2.07999992f, -18.914999f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 1.75999999f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        51u, "RTT screen top frame",
        {3.7249999f, 4.75f, -18.914999f},
        {0.0f, 0.0f, 0.0f},
        {4.49000025f, 0.159999996f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        52u, "RTT screen bottom frame",
        {3.7249999f, 3.34000015f, -18.914999f},
        {0.0f, 0.0f, 0.0f},
        {4.49000025f, 0.159999996f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        53u, "RTT screen left frame",
        {1.56999981f, 4.04500008f, -18.914999f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 1.40999997f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        54u, "RTT screen right frame",
        {5.88000011f, 4.04500008f, -18.914999f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 1.40999997f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        55u, "Ceiling PTZ mount",
        {1.22000003f, 5.5f, -9.60000038f},
        {0.0f, 0.0f, 0.0f},
        {0.340000004f, 0.159999996f, 0.340000004f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Ceiling PTZ camera"
    },
    HardcodedDefaultEntry{
        56u, "Ceiling PTZ dome",
        {1.14234972f, 5.39662886f, -9.45728302f},
        {0.622594178f, 2.64330125f, 0.0f},
        {0.379999995f, 0.300000012f, 0.379999995f},
        {1.0f, 1.0f, 1.0f},
        "UV sphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Ceiling PTZ camera"
    },
    HardcodedDefaultEntry{
        57u, "Ceiling PTZ lens",
        {1.18117487f, 5.25831413f, -9.5286417f},
        {2.19339061f, 2.64330125f, 0.0f},
        {0.140000001f, 0.239999995f, 0.140000001f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Ceiling PTZ camera"
    },
    HardcodedDefaultEntry{
        58u, "Outdoor security-camera wall bracket",
        {-15.7448425f, 6.741642f, 12.6831579f},
        {0.182605699f, 1.81191397f, 0.0f},
        {0.119999997f, 0.119999997f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Outdoor box camera"
    },
    HardcodedDefaultEntry{
        59u, "Outdoor security-camera body",
        {-15.3437738f, 6.66537333f, 12.5845346f},
        {0.182605699f, 1.81191397f, 0.0f},
        {0.419999987f, 0.280000001f, 0.620000005f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Outdoor box camera"
    },
    HardcodedDefaultEntry{
        60u, "Outdoor security-camera sun hood",
        {-15.1909857f, 6.81631804f, 12.5469637f},
        {0.182605699f, 1.81191397f, 0.0f},
        {0.479999989f, 0.0799999982f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Outdoor box camera"
    },
    HardcodedDefaultEntry{
        61u, "Outdoor security-camera lens",
        {-15.0954924f, 6.61815929f, 12.5234814f},
        {1.75340211f, 1.81191397f, 0.0f},
        {0.170000002f, 0.25f, 0.170000002f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Outdoor box camera"
    },
    HardcodedDefaultEntry{
        62u, "Camera-attached player humanoid",
        {0.0f, 0.0f, 0.0f},
        {0.0f, 1.06744432f, 0.0f},
        {0.720000029f, 0.720000029f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Humanoid", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Player model"
    },
    HardcodedDefaultEntry{
        63u, "Display pedestal",
        {11.25f, 0.75999999f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {5.0f, 0.720000029f, 3.70000005f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        64u, "Brushed aluminum pedestal trim",
        {11.25f, 1.14160001f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {5.19999981f, 0.0599999987f, 3.84799981f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        65u, "Transmission crystal lens",
        {9.64999962f, 1.95000005f, -14.0f},
        {0.209439516f, 1126.72522f, -0.139626339f},
        {1.12f, 1.45000005f, 1.12f},
        {1.0f, 1.0f, 1.0f},
        "Icosphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        66u, "Clearcoat automotive form",
        {11.25f, 1.64999998f, -14.0f},
        {0.0f, 1721.07141f, 0.0f},
        {2.1500001f, 1.14999998f, 1.14999998f},
        {1.0f, 1.0f, 1.0f},
        "Capsule", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        67u, "Carbon fiber inner plinth",
        {11.25f, 0.949999988f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {3.0f, 0.419999987f, 1.64999998f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        68u, "Correctly oriented light base",
        {-13.8000002f, 0.219999999f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.419999987f, 0.419999987f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        69u, "Correctly oriented light pole",
        {-13.8000002f, 2.29999995f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 4.3499999f, 0.159999996f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        70u, "Correctly oriented light crossarm",
        {-13.8000002f, 4.42000008f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {1.54999995f, 0.140000001f, 0.140000001f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        71u, "Light pendant",
        {-14.4200001f, 4.11999989f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.0799999982f, 0.479999989f, 0.0799999982f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        72u, "Transmission lamp globe",
        {-14.4200001f, 3.77999997f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.340000004f, 0.340000004f, 0.340000004f},
        {1.0f, 1.0f, 1.0f},
        "UV sphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        73u, "Emissive lamp bulb",
        {-14.4200001f, 3.77999997f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.119999997f, 0.119999997f, 0.119999997f},
        {1.0f, 1.0f, 1.0f},
        "Icosphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        74u, "Light pendant",
        {-13.1800003f, 4.11999989f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.0799999982f, 0.479999989f, 0.0799999982f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        75u, "Transmission lamp globe",
        {-13.1800003f, 3.77999997f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.340000004f, 0.340000004f, 0.340000004f},
        {1.0f, 1.0f, 1.0f},
        "UV sphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        76u, "Emissive lamp bulb",
        {-13.1800003f, 3.77999997f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.119999997f, 0.119999997f, 0.119999997f},
        {1.0f, 1.0f, 1.0f},
        "Icosphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        77u, "Correctly oriented light base",
        {13.8000002f, 0.219999999f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.419999987f, 0.419999987f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        78u, "Correctly oriented light pole",
        {13.8000002f, 2.29999995f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 4.3499999f, 0.159999996f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        79u, "Correctly oriented light crossarm",
        {13.8000002f, 4.42000008f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {1.54999995f, 0.140000001f, 0.140000001f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        80u, "Light pendant",
        {13.1800003f, 4.11999989f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.0799999982f, 0.479999989f, 0.0799999982f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        81u, "Transmission lamp globe",
        {13.1800003f, 3.77999997f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.340000004f, 0.340000004f, 0.340000004f},
        {1.0f, 1.0f, 1.0f},
        "UV sphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        82u, "Emissive lamp bulb",
        {13.1800003f, 3.77999997f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.119999997f, 0.119999997f, 0.119999997f},
        {1.0f, 1.0f, 1.0f},
        "Icosphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        83u, "Light pendant",
        {14.4200001f, 4.11999989f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.0799999982f, 0.479999989f, 0.0799999982f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        84u, "Transmission lamp globe",
        {14.4200001f, 3.77999997f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.340000004f, 0.340000004f, 0.340000004f},
        {1.0f, 1.0f, 1.0f},
        "UV sphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        85u, "Emissive lamp bulb",
        {14.4200001f, 3.77999997f, -7.0f},
        {0.0f, 0.0f, 0.0f},
        {0.119999997f, 0.119999997f, 0.119999997f},
        {1.0f, 1.0f, 1.0f},
        "Icosphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        86u, "Unified courtyard platform",
        {-3.76450729f, 0.0533542633f, 1.41242027f},
        {0.0f, 0.0f, 0.0f},
        {28.3115349f, 0.353831798f, 21.4014912f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Courtyard platform"
    },
    HardcodedDefaultEntry{
        87u, "South retaining face",
        {-2.79924393f, -0.379999995f, 12.3770266f},
        {0.0f, 0.0f, 0.0f},
        {25.0451355f, 0.720000029f, 1.20233059f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Courtyard platform"
    },
    HardcodedDefaultEntry{
        88u, "West retaining face",
        {-18.0121613f, -0.379999995f, 1.33783722f},
        {0.0f, 0.0f, 0.0f},
        {0.439999998f, 0.720000029f, 21.4014912f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Courtyard platform"
    },
    HardcodedDefaultEntry{
        89u, "RTT screen top frame",
        {5.5f, 3.48000002f, 8.36499977f},
        {0.0f, 0.0f, 0.0f},
        {4.74000025f, 0.159999996f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        90u, "RTT screen bottom frame",
        {5.5f, 0.620000005f, 8.36499977f},
        {0.0f, 0.0f, 0.0f},
        {4.74000025f, 0.159999996f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        91u, "RTT screen left frame",
        {3.22000003f, 2.04999995f, 8.36499977f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 2.86000013f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        92u, "RTT screen right frame",
        {7.77999973f, 2.04999995f, 8.36499977f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 2.86000013f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        93u, "Opaque planar mirror backing",
        {5.5f, 2.04999995f, 8.51499939f},
        {0.0f, 0.0f, 0.0f},
        {4.55999994f, 2.8599999f, 0.159999996f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        94u, "Mirror support left",
        {3.45000005f, 0.349999994f, 8.5199995f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 1.35000002f, 0.219999999f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        95u, "Mirror support right",
        {7.55000019f, 0.349999994f, 8.5199995f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 1.35000002f, 0.219999999f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        96u, "Campfire stone ring",
        {-14.1800003f, 0.25999999f, 8.0f},
        {0.0f, 0.0f, -0.104719758f},
        {0.239999995f, 0.180000007f, 0.200000003f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Campfire pit"
    },
    HardcodedDefaultEntry{
        97u, "Campfire stone ring",
        {-14.463769f, 0.219999999f, 8.44995117f},
        {0.139626339f, 0.907571197f, -0.052359879f},
        {0.189999998f, 0.140000001f, 0.170000002f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Campfire pit"
    },
    HardcodedDefaultEntry{
        98u, "Campfire stone ring",
        {-14.8576088f, 0.219999999f, 8.8075428f},
        {0.279252678f, 1.81514239f, 0.0f},
        {0.239999995f, 0.180000007f, 0.200000003f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Campfire pit"
    },
    HardcodedDefaultEntry{
        99u, "Campfire stone ring",
        {-15.3500004f, 0.25999999f, 8.60621738f},
        {0.0f, 2.72271371f, 0.052359879f},
        {0.189999998f, 0.140000001f, 0.170000002f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Campfire pit"
    },
    HardcodedDefaultEntry{
        100u, "Campfire stone ring",
        {-15.7705479f, 0.219999999f, 8.28045654f},
        {0.139626339f, 3.63028479f, -0.104719758f},
        {0.239999995f, 0.180000007f, 0.200000003f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Campfire pit"
    },
    HardcodedDefaultEntry{
        101u, "Campfire stone ring",
        {-15.6577845f, 0.219999999f, 7.76058626f},
        {0.279252678f, 4.5378561f, -0.052359879f},
        {0.189999998f, 0.140000001f, 0.170000002f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Campfire pit"
    },
    HardcodedDefaultEntry{
        102u, "Campfire stone ring",
        {-15.4099998f, 0.25999999f, 7.28985929f},
        {0.0f, 5.44542742f, 0.0f},
        {0.239999995f, 0.180000007f, 0.200000003f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Campfire pit"
    },
    HardcodedDefaultEntry{
        103u, "Campfire stone ring",
        {-14.8784466f, 0.219999999f, 7.31063461f},
        {0.139626339f, 6.35299873f, 0.052359879f},
        {0.189999998f, 0.140000001f, 0.170000002f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Campfire pit"
    },
    HardcodedDefaultEntry{
        104u, "Campfire stone ring",
        {-14.3718433f, 0.219999999f, 7.47291422f},
        {0.279252678f, 7.26056957f, -0.104719758f},
        {0.239999995f, 0.180000007f, 0.200000003f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Campfire pit"
    },
    HardcodedDefaultEntry{
        105u, "Campfire crossed log A",
        {-15.0f, 0.350000024f, 8.0f},
        {0.0f, 0.628318548f, 0.0f},
        {1.04999995f, 0.140000001f, 0.159999996f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Campfire pit"
    },
    HardcodedDefaultEntry{
        106u, "Campfire crossed log B",
        {-15.0f, 0.379999995f, 8.0f},
        {0.0f, -0.628318548f, 0.0f},
        {1.04999995f, 0.140000001f, 0.159999996f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Campfire pit"
    },
    HardcodedDefaultEntry{
        107u, "Campfire emissive core",
        {-15.0f, 0.600000024f, 8.0f},
        {0.0f, 0.0f, 0.0f},
        {0.300000012f, 0.419999987f, 0.300000012f},
        {1.0f, 1.0f, 1.0f},
        "Icosphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Campfire pit"
    },
    HardcodedDefaultEntry{
        108u, "Campfire bench connected seat",
        {-15.0f, 0.779999971f, 10.3500004f},
        {0.0f, 4.3e-08f, 0.0f},
        {1.84000003f, 0.119999997f, 0.5f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench south"
    },
    HardcodedDefaultEntry{
        109u, "Campfire bench connected backrest",
        {-15.0f, 1.29999995f, 10.5852051f},
        {0.0f, 4.3e-08f, 0.0f},
        {1.77999997f, 0.340000004f, 0.0900000036f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench south"
    },
    HardcodedDefaultEntry{
        110u, "Campfire bench leg",
        {-15.4738693f, 0.50999999f, 10.3500004f},
        {0.0f, 4.3e-08f, 0.0f},
        {0.180000007f, 0.579999983f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench south"
    },
    HardcodedDefaultEntry{
        111u, "Campfire bench back support",
        {-15.4738693f, 1.01999998f, 10.6499996f},
        {0.0f, 4.3e-08f, 0.0f},
        {0.129999995f, 0.579999983f, 0.129999995f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench south"
    },
    HardcodedDefaultEntry{
        112u, "Campfire bench end brace",
        {-15.8599997f, 0.949999988f, 10.3800001f},
        {0.0f, 4.3e-08f, -1.57079637f},
        {0.200000003f, 0.0799999982f, 0.400000006f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench south"
    },
    HardcodedDefaultEntry{
        113u, "Campfire bench leg",
        {-14.4778366f, 0.50999999f, 10.3500004f},
        {0.0f, 4.3e-08f, 0.0f},
        {0.180000007f, 0.579999983f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench south"
    },
    HardcodedDefaultEntry{
        114u, "Campfire bench back support",
        {-14.4778366f, 1.01999998f, 10.6499996f},
        {0.0f, 4.3e-08f, 0.0f},
        {0.129999995f, 0.579999983f, 0.129999995f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench south"
    },
    HardcodedDefaultEntry{
        115u, "Campfire bench end brace",
        {-14.1400003f, 0.949999988f, 10.3800001f},
        {0.0f, 4.3e-08f, -1.57079637f},
        {0.200000003f, 0.0799999982f, 0.400000006f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench south"
    },
    HardcodedDefaultEntry{
        116u, "Campfire bench longitudinal stretcher",
        {-15.0f, 0.439999998f, 10.3500004f},
        {0.0f, 4.3e-08f, 0.0f},
        {1.03999996f, 0.0900000036f, 0.100000001f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench south"
    },
    HardcodedDefaultEntry{
        117u, "Campfire bench connected seat",
        {-15.0f, 0.779999971f, 5.64999962f},
        {0.0f, 3.14159274f, 0.0f},
        {1.84000003f, 0.119999997f, 0.5f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench north"
    },
    HardcodedDefaultEntry{
        118u, "Campfire bench connected backrest",
        {-15.0f, 1.29999995f, 5.41479492f},
        {0.0f, 3.14159274f, 0.0f},
        {1.77999997f, 0.340000004f, 0.0900000036f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench north"
    },
    HardcodedDefaultEntry{
        119u, "Campfire bench leg",
        {-14.5261307f, 0.50999999f, 5.64999962f},
        {0.0f, 3.14159274f, 0.0f},
        {0.180000007f, 0.579999983f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench north"
    },
    HardcodedDefaultEntry{
        120u, "Campfire bench back support",
        {-14.5261307f, 1.01999998f, 5.35000038f},
        {0.0f, 3.14159274f, 0.0f},
        {0.129999995f, 0.579999983f, 0.129999995f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench north"
    },
    HardcodedDefaultEntry{
        121u, "Campfire bench end brace",
        {-14.1400003f, 0.949999988f, 5.61999989f},
        {0.0f, 3.14159274f, -1.57079637f},
        {0.200000003f, 0.0799999982f, 0.400000006f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench north"
    },
    HardcodedDefaultEntry{
        122u, "Campfire bench leg",
        {-15.5221634f, 0.50999999f, 5.64999962f},
        {0.0f, 3.14159274f, 0.0f},
        {0.180000007f, 0.579999983f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench north"
    },
    HardcodedDefaultEntry{
        123u, "Campfire bench back support",
        {-15.5221634f, 1.01999998f, 5.35000038f},
        {0.0f, 3.14159274f, 0.0f},
        {0.129999995f, 0.579999983f, 0.129999995f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench north"
    },
    HardcodedDefaultEntry{
        124u, "Campfire bench end brace",
        {-15.8599997f, 0.949999988f, 5.61999989f},
        {0.0f, 3.14159274f, -1.57079637f},
        {0.200000003f, 0.0799999982f, 0.400000006f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench north"
    },
    HardcodedDefaultEntry{
        125u, "Campfire bench longitudinal stretcher",
        {-15.0f, 0.439999998f, 5.64999962f},
        {0.0f, 3.14159274f, 0.0f},
        {1.03999996f, 0.0900000036f, 0.100000001f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench north"
    },
    HardcodedDefaultEntry{
        126u, "Campfire bench connected seat",
        {-12.6499996f, 0.779999971f, 8.0f},
        {0.0f, 1.57079637f, 0.0f},
        {1.84000003f, 0.119999997f, 0.5f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench east"
    },
    HardcodedDefaultEntry{
        127u, "Campfire bench connected backrest",
        {-12.4147949f, 1.29999995f, 8.0f},
        {0.0f, 1.57079637f, 0.0f},
        {1.77999997f, 0.340000004f, 0.0900000036f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench east"
    },
    HardcodedDefaultEntry{
        128u, "Campfire bench leg",
        {-12.6499996f, 0.50999999f, 8.47386932f},
        {0.0f, 1.57079637f, 0.0f},
        {0.180000007f, 0.579999983f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench east"
    },
    HardcodedDefaultEntry{
        129u, "Campfire bench back support",
        {-12.3500004f, 1.01999998f, 8.47386932f},
        {0.0f, 1.57079637f, 0.0f},
        {0.129999995f, 0.579999983f, 0.129999995f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench east"
    },
    HardcodedDefaultEntry{
        130u, "Campfire bench end brace",
        {-12.6199999f, 0.949999988f, 8.85999966f},
        {0.0f, 1.57079637f, -1.57079637f},
        {0.200000003f, 0.0799999982f, 0.400000006f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench east"
    },
    HardcodedDefaultEntry{
        131u, "Campfire bench leg",
        {-12.6499996f, 0.50999999f, 7.47783661f},
        {0.0f, 1.57079637f, 0.0f},
        {0.180000007f, 0.579999983f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench east"
    },
    HardcodedDefaultEntry{
        132u, "Campfire bench back support",
        {-12.3500004f, 1.01999998f, 7.47783661f},
        {0.0f, 1.57079637f, 0.0f},
        {0.129999995f, 0.579999983f, 0.129999995f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench east"
    },
    HardcodedDefaultEntry{
        133u, "Campfire bench end brace",
        {-12.6199999f, 0.949999988f, 7.13999987f},
        {0.0f, 1.57079637f, -1.57079637f},
        {0.200000003f, 0.0799999982f, 0.400000006f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench east"
    },
    HardcodedDefaultEntry{
        134u, "Campfire bench longitudinal stretcher",
        {-12.6499996f, 0.439999998f, 8.0f},
        {0.0f, 1.57079637f, 0.0f},
        {1.03999996f, 0.0900000036f, 0.100000001f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench east"
    },
    HardcodedDefaultEntry{
        135u, "Campfire bench connected seat",
        {-17.3500004f, 0.779999971f, 8.0f},
        {0.0f, -1.57079625f, 0.0f},
        {1.84000003f, 0.119999997f, 0.5f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench west"
    },
    HardcodedDefaultEntry{
        136u, "Campfire bench connected backrest",
        {-17.5852051f, 1.29999995f, 8.0f},
        {0.0f, -1.57079625f, 0.0f},
        {1.77999997f, 0.340000004f, 0.0900000036f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench west"
    },
    HardcodedDefaultEntry{
        137u, "Campfire bench leg",
        {-17.3500004f, 0.50999999f, 7.52613068f},
        {0.0f, -1.57079625f, 0.0f},
        {0.180000007f, 0.579999983f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench west"
    },
    HardcodedDefaultEntry{
        138u, "Campfire bench back support",
        {-17.6499996f, 1.01999998f, 7.52613068f},
        {0.0f, -1.57079625f, 0.0f},
        {0.129999995f, 0.579999983f, 0.129999995f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench west"
    },
    HardcodedDefaultEntry{
        139u, "Campfire bench end brace",
        {-17.3799992f, 0.949999988f, 7.14000034f},
        {0.0f, -1.57079625f, -1.57079637f},
        {0.200000003f, 0.0799999982f, 0.400000006f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench west"
    },
    HardcodedDefaultEntry{
        140u, "Campfire bench leg",
        {-17.3500004f, 0.50999999f, 8.52216339f},
        {0.0f, -1.57079625f, 0.0f},
        {0.180000007f, 0.579999983f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench west"
    },
    HardcodedDefaultEntry{
        141u, "Campfire bench back support",
        {-17.6499996f, 1.01999998f, 8.52216339f},
        {0.0f, -1.57079625f, 0.0f},
        {0.129999995f, 0.579999983f, 0.129999995f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench west"
    },
    HardcodedDefaultEntry{
        142u, "Campfire bench end brace",
        {-17.3799992f, 0.949999988f, 8.85999966f},
        {0.0f, -1.57079625f, -1.57079637f},
        {0.200000003f, 0.0799999982f, 0.400000006f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench west"
    },
    HardcodedDefaultEntry{
        143u, "Campfire bench longitudinal stretcher",
        {-17.3500004f, 0.439999998f, 8.0f},
        {0.0f, -1.57079625f, 0.0f},
        {1.03999996f, 0.0900000036f, 0.100000001f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camp bench west"
    },
    HardcodedDefaultEntry{
        144u, "Flag pole base",
        {-17.082653f, 0.25f, -3.5f},
        {0.0f, 0.0f, 0.0f},
        {0.550000012f, 0.419999987f, 0.550000012f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "American flag assembly"
    },
    HardcodedDefaultEntry{
        145u, "Flag pole",
        {-17.082653f, 3.25f, -3.5f},
        {0.0f, 0.0f, 0.0f},
        {0.119999997f, 6.19999981f, 0.119999997f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "American flag assembly"
    },
    HardcodedDefaultEntry{
        146u, "Flag pole halyard",
        {-16.9826527f, 3.3499999f, -3.5f},
        {0.0f, 0.0f, 0.0f},
        {0.0179999992f, 5.69999981f, 0.0179999992f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "American flag assembly"
    },
    HardcodedDefaultEntry{
        147u, "Flag pole finial",
        {-17.082653f, 6.48000002f, -3.5f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 0.159999996f, 0.159999996f},
        {1.0f, 1.0f, 1.0f},
        "UV sphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "American flag assembly"
    },
    HardcodedDefaultEntry{
        148u, "Unity flag pole base",
        {19.3544273f, 0.25f, -3.5f},
        {0.0f, 0.0f, 0.0f},
        {0.550000012f, 0.419999987f, 0.550000012f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Israeli flag assembly"
    },
    HardcodedDefaultEntry{
        149u, "Unity flag pole",
        {19.3544273f, 3.25f, -3.5f},
        {0.0f, 0.0f, 0.0f},
        {0.119999997f, 6.19999981f, 0.119999997f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Israeli flag assembly"
    },
    HardcodedDefaultEntry{
        150u, "Unity flag pole halyard",
        {19.254427f, 3.3499999f, -3.5f},
        {0.0f, 0.0f, 0.0f},
        {0.0179999992f, 5.69999981f, 0.0179999992f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Israeli flag assembly"
    },
    HardcodedDefaultEntry{
        151u, "Unity flag pole finial",
        {19.3544273f, 6.48000002f, -3.5f},
        {0.0f, 0.0f, 0.0f},
        {0.159999996f, 0.159999996f, 0.159999996f},
        {1.0f, 1.0f, 1.0f},
        "UV sphere", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Israeli flag assembly"
    },
    HardcodedDefaultEntry{
        152u, "Awning support beam",
        {2.1922493f, 5.75f, -8.77112961f},
        {0.0f, 0.0f, 0.0f},
        {4.19999981f, 0.119999997f, 0.119999997f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Entrance awning"
    },
    HardcodedDefaultEntry{
        153u, "Instanced loading bay slab",
        {15.5594616f, 0.0417575836f, -4.93243027f},
        {0.0f, 0.0f, 0.0f},
        {10.7987032f, 0.280000001f, 8.56418896f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        154u, "Wooden barrel lower stave section",
        {21.0f, 0.780000031f, -8.32499981f},
        {1.57079637f, 0.0f, 0.0f},
        {1.34000003f, 1.34000003f, 0.560000002f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        155u, "Wooden barrel bulged center section",
        {21.0f, 1.34000003f, -8.32499981f},
        {1.57079637f, 0.0f, 0.0f},
        {1.51999998f, 1.51999998f, 0.74000001f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        156u, "Wooden barrel upper stave section",
        {21.0f, 1.9000001f, -8.32499981f},
        {1.57079637f, 0.0f, 0.0f},
        {1.34000003f, 1.34000003f, 0.560000002f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        157u, "Barrel forged-metal hoop",
        {21.0f, 0.540000021f, -8.32499981f},
        {1.57079637f, 0.0f, 0.0f},
        {1.05999994f, 1.05999994f, 0.300000012f},
        {1.0f, 1.0f, 1.0f},
        "Torus", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        158u, "Barrel forged-metal hoop",
        {21.0f, 0.970000029f, -8.32499981f},
        {1.57079637f, 0.0f, 0.0f},
        {1.05999994f, 1.05999994f, 0.300000012f},
        {1.0f, 1.0f, 1.0f},
        "Torus", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        159u, "Barrel forged-metal hoop",
        {21.0f, 1.71000004f, -8.32499981f},
        {1.57079637f, 0.0f, 0.0f},
        {1.05999994f, 1.05999994f, 0.300000012f},
        {1.0f, 1.0f, 1.0f},
        "Torus", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        160u, "Barrel forged-metal hoop",
        {21.0f, 2.1400001f, -8.32499981f},
        {1.57079637f, 0.0f, 0.0f},
        {1.05999994f, 1.05999994f, 0.300000012f},
        {1.0f, 1.0f, 1.0f},
        "Torus", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        161u, "Wooden barrel top cap",
        {21.0f, 2.20000005f, -8.32499981f},
        {1.57079637f, 0.0f, 0.0f},
        {1.22000003f, 1.22000003f, 0.100000001f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        162u, "Wooden barrel bottom cap",
        {21.0f, 0.480000019f, -8.32499981f},
        {1.57079637f, 0.0f, 0.0f},
        {1.22000003f, 1.22000003f, 0.100000001f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        163u, "Reflecting pool submerged bed",
        {13.8765125f, -0.300000072f, 4.99381876f},
        {0.0f, -1.57686007f, 0.0f},
        {11.1000004f, 0.439999998f, 8.09999847f},
        {1.0f, 1.0f, 0.850000024f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool"
    },
    HardcodedDefaultEntry{
        164u, "Reflecting pool north coping",
        {17.4264393f, 0.0799999982f, 5.01534271f},
        {0.0f, -1.57686007f, 0.0f},
        {11.8000002f, 0.379999995f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool"
    },
    HardcodedDefaultEntry{
        165u, "Reflecting pool south coping",
        {10.3265791f, 0.0799999982f, 4.97228813f},
        {0.0f, -1.57686007f, 0.0f},
        {11.8000002f, 0.379999995f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool"
    },
    HardcodedDefaultEntry{
        166u, "Reflecting pool west coping",
        {13.9110718f, 0.0799999982f, -0.70606184f},
        {0.0f, -1.57686007f, 0.0f},
        {0.419999987f, 0.379999995f, 6.69999981f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool"
    },
    HardcodedDefaultEntry{
        167u, "Reflecting pool east coping",
        {13.8419399f, 0.0799999982f, 10.6937065f},
        {0.0f, -1.57686007f, 0.0f},
        {0.419999987f, 0.379999995f, 6.69999981f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool"
    },
    HardcodedDefaultEntry{
        168u, "Pool fountain plinth",
        {13.8765125f, 0.220000029f, 4.99381876f},
        {0.0f, -1.57686007f, 0.0f},
        {0.850000024f, 0.5f, 0.850000024f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool"
    },
    HardcodedDefaultEntry{
        169u, "Pool brushed metal sculpture",
        {13.8765125f, 1.45000005f, 4.99381876f},
        {0.0f, -1.57686007f, 0.0f},
        {1.75f, 1.75f, 1.75f},
        {1.0f, 1.0f, 1.0f},
        "Torus", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool"
    },
    HardcodedDefaultEntry{
        170u, "Perimeter tree",
        {27.0f, -1.0f, 12.0f},
        {0.0f, -0.383972466f, 0.0f},
        {1.35000002f, 1.35000002f, 1.35000002f},
        {1.0f, 1.0f, 1.0f},
        "Pine tree", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        171u, "Perimeter tree",
        {25.0f, -1.0f, -21.0f},
        {0.0f, 1.08210421f, 0.0f},
        {1.35000002f, 1.35000002f, 1.35000002f},
        {1.0f, 1.0f, 1.0f},
        "Oak tree", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        172u, "Perimeter tree",
        {-25.0f, -1.0f, -22.0f},
        {0.0f, 1.83259583f, 0.0f},
        {1.41999996f, 1.41999996f, 1.41999996f},
        {1.0f, 1.0f, 1.0f},
        "Pine tree", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        173u, "Perimeter tree",
        {-8.0f, -1.0f, 24.0f},
        {0.0f, 0.610865295f, 0.0f},
        {1.25f, 1.25f, 1.25f},
        {1.0f, 1.0f, 1.0f},
        "Oak tree", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        174u, "Perimeter tree",
        {8.0f, -1.0f, 24.0f},
        {0.0f, -0.69813174f, 0.0f},
        {1.20000005f, 1.20000005f, 1.20000005f},
        {1.0f, 1.0f, 1.0f},
        "Pine tree", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        175u, "Pool rock cluster A",
        {22.3999996f, -0.419999987f, 4.4000001f},
        {0.0f, -0.383972466f, 0.0f},
        {1.20000005f, 1.20000005f, 1.20000005f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Pool rocks"
    },
    HardcodedDefaultEntry{
        176u, "Pool rock cluster B",
        {24.0f, -0.460000008f, 5.30000019f},
        {0.0f, 0.593411982f, 0.0f},
        {0.920000017f, 0.920000017f, 0.920000017f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Pool rocks"
    },
    HardcodedDefaultEntry{
        177u, "Lake rock cluster A",
        {-18.3999996f, -1.79310942f, -27.2000008f},
        {0.0f, 0.314159274f, 0.0f},
        {1.27999997f, 1.27999997f, 1.27999997f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Lake rocks"
    },
    HardcodedDefaultEntry{
        178u, "Lake rock cluster B",
        {-16.6000004f, -1.75310946f, -28.3999996f},
        {0.0f, -0.628318548f, 0.0f},
        {0.959999979f, 0.959999979f, 0.959999979f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Lake rocks"
    },
    HardcodedDefaultEntry{
        179u, "Distant rock cluster",
        {19.2756786f, -0.80405426f, -23.6973f},
        {0.0f, -0.488692224f, 0.0f},
        {1.10000002f, 1.10000002f, 1.10000002f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Distant rocks"
    },
    HardcodedDefaultEntry{
        180u, "[Effect] Bordered architectural reflecting pool",
        {13.8761349f, -0.0799999982f, 5.05563164f},
        {0.0f, -1.57686007f, 0.0f},
        {5.44999981f, 1.0f, 3.1500001f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.5f, 0.579999983f, 0.0599999987f, 0.100000001f},
        "Architectural pool"
    },
    HardcodedDefaultEntry{
        181u, "[Effect] Distant terrain lake",
        {3.49999881f, -0.980000079f, -30.0f},
        {0.0f, 0.0f, 0.0f},
        {32.9008484f, 1.0f, 27.904562f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.5f, 0.479999989f, 0.104999997f, 0.889999986f},
        "Distant terrain water"
    },
    HardcodedDefaultEntry{
        182u, "[Effect] Detailed American flag cloth",
        {-17.0126534f, 6.17999983f, -3.5f},
        {0.0f, 0.0f, 0.0f},
        {3.79999995f, 2.0f, 0.25f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {2.4000001f, 0.699999988f, 0.159999996f, 0.0f},
        "American flag assembly"
    },
    HardcodedDefaultEntry{
        183u, "[Effect] Detailed Israeli flag cloth",
        {19.2844276f, 6.17999983f, -3.5f},
        {0.0f, 0.0f, 0.0f},
        {3.79999995f, 2.0f, 0.25f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {2.4000001f, 0.699999988f, 0.159999996f, 0.0f},
        "Israeli flag assembly"
    },
    HardcodedDefaultEntry{
        184u, "[Effect] Woven entrance awning cloth",
        {0.192249298f, 5.67999983f, -8.70112896f},
        {0.0f, 0.0f, 0.0f},
        {4.0f, 1.35000002f, 0.25f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {1.10000002f, 0.720000029f, 0.075000003f, 0.0f},
        "Entrance awning"
    },
    HardcodedDefaultEntry{
        185u, "[Effect] Live security-camera render target",
        {2.1500001f, 1.27999997f, -18.8799992f},
        {0.0f, 0.0f, 0.0f},
        {2.75f, 1.60000002f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Security RTT display"
    },
    HardcodedDefaultEntry{
        186u, "[Effect] Overhead site-camera render target",
        {5.30000019f, 1.27999997f, -18.8799992f},
        {0.0f, 0.0f, 0.0f},
        {2.75f, 1.60000002f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Overhead RTT display"
    },
    HardcodedDefaultEntry{
        187u, "[Effect] Ceiling security-camera master display",
        {3.7249999f, 3.42000008f, -18.8799992f},
        {0.0f, 0.0f, 0.0f},
        {4.1500001f, 1.25f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Ceiling RTT display"
    },
    HardcodedDefaultEntry{
        188u, "[Effect] Freestanding planar mirror render target",
        {5.5f, 0.699999988f, 8.39999962f},
        {0.0f, 0.0f, 0.0f},
        {4.4000001f, 2.70000005f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Planar mirror display"
    },
    HardcodedDefaultEntry{
        189u, "[Effect] Point light 1",
        {-11.1999998f, 4.0f, -12.1999998f},
        {0.0f, 0.0f, 0.0f},
        {1.75f, 1.75f, 1.75f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {7.0f, 1.53999996f, 0.0f, 0.0f},
        "Point lights"
    },
    HardcodedDefaultEntry{
        190u, "[Effect] Point light 2",
        {-3.70000005f, 4.0999999f, -12.0f},
        {0.0f, 0.0f, 0.0f},
        {1.75f, 1.75f, 1.75f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {8.70693207f, 1.45200002f, 0.0f, 0.0f},
        "Point lights"
    },
    HardcodedDefaultEntry{
        191u, "[Effect] Point light 3",
        {10.8000002f, 4.0f, -12.1000004f},
        {0.0f, 0.0f, 0.0f},
        {1.875f, 1.875f, 1.875f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {7.5f, 1.88999987f, 0.0f, 0.0f},
        "Point lights"
    },
    HardcodedDefaultEntry{
        192u, "[Effect] Point light 4",
        {-15.0f, 1.25f, 8.0f},
        {0.0f, 0.0f, 0.0f},
        {1.375f, 1.375f, 1.375f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {5.5f, 3.96109867f, 0.0f, 0.0f},
        "Point lights"
    },
    HardcodedDefaultEntry{
        193u, "[Effect] Red dual-sided spotlight",
        {1.04999995f, 4.55000019f, -13.1000004f},
        {-0.532640159f, -0.630401433f, 0.0f},
        {2.25f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {15.0f, 16.0f, 0.949999988f, 0.800000012f},
        "Camera room spotlights"
    },
    HardcodedDefaultEntry{
        194u, "[Effect] Blue dual-sided spotlight",
        {6.44999981f, 4.55000019f, -13.1000004f},
        {-0.532640159f, 0.630401433f, 0.0f},
        {2.25f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {15.0f, 16.0f, 0.949999988f, 0.800000012f},
        "Camera room spotlights"
    },
    HardcodedDefaultEntry{
        195u, "[Effect] Main terrain foliage region",
        {0.0f, -1.0f, 0.0f},
        {0.0f, 0.0f, 0.0f},
        {20.0f, 1.0f, 20.0f},
        {1.70000005f, 1.0f, 1.70000005f},
        "Cube", true, false,
        {3.0f, 1.0f, 1.0f, 1.0f},
        "Terrain foliage"
    },
    HardcodedDefaultEntry{
        196u, "[Effect] Campfire particle emitter",
        {-15.0f, 0.200000003f, 8.0f},
        {0.0f, 0.0f, 0.0f},
        {1.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {1.0f, 1.0f, 0.0f, 0.0f},
        "Campfire pit"
    },
    HardcodedDefaultEntry{
        197u, "[Effect] Pool light-mote emitter",
        {13.8765125f, 0.180000007f, 4.99381876f},
        {0.0f, -1.57686007f, 0.0f},
        {1.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {1.0f, 1.0f, 0.0f, 0.0f},
        "Architectural pool"
    },
    HardcodedDefaultEntry{
        198u, "[Effect] Pool mist emitter",
        {13.8765125f, 0.119999997f, 4.99381876f},
        {0.0f, -1.57686007f, 0.0f},
        {1.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {1.0f, 1.0f, 0.0f, 0.0f},
        "Architectural pool"
    },
    HardcodedDefaultEntry{
        199u, "[Effect] Scene label 1",
        {-11.25f, 6.82000017f, -8.35000038f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        200u, "[Effect] Scene label 2",
        {-3.75f, 6.82000017f, -8.35000038f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        201u, "[Effect] Scene label 3",
        {3.75f, 6.82000017f, -8.35000038f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        202u, "[Effect] Scene label 4",
        {11.25f, 6.82000017f, -8.35000038f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        203u, "[Effect] Scene label 5",
        {5.5f, 4.0f, 8.39999962f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        204u, "[Effect] Scene label 6",
        {-15.0f, 2.1500001f, 8.0f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        205u, "[Effect] Scene label 7",
        {-18.2999992f, 7.1500001f, -3.20000005f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        206u, "[Effect] Scene label 8",
        {18.6000004f, 2.6500001f, -10.0f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        207u, "[Effect] Scene label 9",
        {16.0f, 2.25f, 5.0f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        208u, "[Effect] Scene label 10",
        {0.0f, 1.25f, 22.0f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        209u, "[Effect] Scene label 11",
        {0.0f, 0.850000024f, -30.0f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        210u, "[Effect] Scene label 12",
        {25.0f, 1.39999998f, 12.0f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        211u, "[Effect] Scene label 13",
        {-11.25f, 3.58734608f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        212u, "[Effect] Scene label 14",
        {-11.25f, 4.6500001f, -16.5499992f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        213u, "[Effect] Scene label 15",
        {-13.1999998f, 3.3499999f, -12.25f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        214u, "[Effect] Scene label 16",
        {-3.75f, 3.04999995f, -13.6000004f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        215u, "[Effect] Scene label 17",
        {3.75f, 4.25f, -16.25f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        216u, "[Effect] Scene label 18",
        {2.1500001f, 3.1500001f, -18.7000008f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        217u, "[Effect] Scene label 19",
        {5.30000019f, 3.1500001f, -18.7000008f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        218u, "[Effect] Scene label 20",
        {3.73000002f, 4.80000019f, -18.7000008f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        219u, "[Effect] Scene label 21",
        {1.22000003f, 5.92000008f, -9.60000038f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        220u, "[Effect] Scene label 22",
        {-15.0f, 7.25f, 12.5f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        221u, "[Effect] Scene label 23",
        {9.64999962f, 3.8499999f, -14.0f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        222u, "[Effect] Scene label 24",
        {-15.0f, 2.54999995f, 8.0f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        223u, "[Effect] Scene label 25",
        {-15.0f, 2.3499999f, 10.75f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        224u, "[Effect] Scene label 26",
        {0.0f, 7.25f, -3.5f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        225u, "[Effect] Scene label 27",
        {5.5f, 3.3499999f, 8.30000019f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        226u, "[Effect] Scene label 28",
        {16.0f, 1.54999995f, 5.0f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        227u, "[Effect] Scene label 29",
        {0.0f, 1.04999995f, -8.89999962f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        228u, "[Effect] Scene label 30",
        {0.0f, 1.35000002f, 18.0f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        229u, "[Effect] Scene label 31",
        {22.5f, 1.64999998f, 12.0f},
        {0.0f, 0.0f, 0.0f},
        {0.649999976f, 0.649999976f, 0.649999976f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        230u, "Hard-edge diagnostic",
        {-3.0f, 1.0f, 14.0f},
        {0.0f, 0.0f, 0.0f},
        {1.25f, 1.25f, 1.25f},
        {1.0f, 1.0f, 1.0f},
        "Hard-edge diagnostic", false, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        231u, "Smooth-edge diagnostic",
        {0.0f, 1.0f, 14.0f},
        {0.0f, 0.0f, 0.0f},
        {1.25f, 1.25f, 1.25f},
        {1.0f, 1.0f, 1.0f},
        "Smooth diagnostic", false, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        232u, "Atlas diagnostic",
        {3.0f, 1.0f, 14.0f},
        {0.0f, 0.0f, 0.0f},
        {1.25f, 1.25f, 1.25f},
        {1.0f, 1.0f, 1.0f},
        "Atlas cube", false, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        ""
    },
    HardcodedDefaultEntry{
        233u, "Outdoor security-camera support pole",
        {-16.2162933f, 3.137043f, 12.7412567f},
        {0.0f, 0.0f, 0.0f},
        {0.180000007f, 8.14261436f, 0.180000007f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Outdoor box camera"
    },
    HardcodedDefaultEntry{
        234u, "Red spotlight ceiling mount",
        {1.04999995f, 4.88999987f, -13.1000004f},
        {0.0f, 0.0f, 0.0f},
        {0.25999999f, 0.119999997f, 0.25999999f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camera room spotlights"
    },
    HardcodedDefaultEntry{
        235u, "Red spotlight rotating yoke",
        {1.04999995f, 4.55000019f, -13.1000004f},
        {0.532640159f, 2.17763376f, 0.0f},
        {0.479999989f, 0.159999996f, 0.159999996f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camera room spotlights"
    },
    HardcodedDefaultEntry{
        236u, "Red dual-sided spotlight lamp",
        {1.04999995f, 4.55000019f, -13.1000004f},
        {-0.532640159f, -0.630401433f, 0.0f},
        {0.200000003f, 0.620000005f, 0.200000003f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {15.0f, 16.0f, 0.949999988f, 0.800000012f},
        "Red camera-room spotlight"
    },
    HardcodedDefaultEntry{
        237u, "Blue spotlight ceiling mount",
        {6.44999981f, 4.88999987f, -13.1000004f},
        {0.0f, 0.0f, 0.0f},
        {0.25999999f, 0.119999997f, 0.25999999f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camera room spotlights"
    },
    HardcodedDefaultEntry{
        238u, "Blue spotlight rotating yoke",
        {6.44999981f, 4.55000019f, -13.1000004f},
        {0.532640159f, -1.56215477f, 0.0f},
        {0.479999989f, 0.159999996f, 0.159999996f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Camera room spotlights"
    },
    HardcodedDefaultEntry{
        239u, "Blue dual-sided spotlight lamp",
        {6.44999981f, 4.55000019f, -13.1000004f},
        {-0.532640159f, 0.630401433f, 0.0f},
        {0.200000003f, 0.620000005f, 0.200000003f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {15.0f, 16.0f, 0.949999988f, 0.800000012f},
        "Blue camera-room spotlight"
    },
    HardcodedDefaultEntry{
        240u, "[Effect] Projector cookie spotlight",
        {-3.75f, 5.55000019f, -10.0f},
        {-0.178092942f, 0.0f, 0.0f},
        {2.0999999f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {14.0f, 10.0f, 0.939999998f, 0.800000012f},
        "Projected cookie spotlight"
    },
    HardcodedDefaultEntry{
        241u, "Projector spotlight ceiling mount",
        {-3.75f, 5.88999987f, -10.0f},
        {0.0f, 0.0f, 0.0f},
        {0.25999999f, 0.119999997f, 0.25999999f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Projected cookie spotlight"
    },
    HardcodedDefaultEntry{
        242u, "Projector spotlight rotating yoke",
        {-3.75f, 5.55000019f, -10.0f},
        {0.178092942f, 3.14159274f, 0.0f},
        {0.479999989f, 0.159999996f, 0.159999996f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Projected cookie spotlight"
    },
    HardcodedDefaultEntry{
        243u, "Projector cookie spotlight lamp",
        {-3.75f, 5.55000019f, -10.0f},
        {-0.178092942f, 0.0f, 0.0f},
        {0.200000003f, 0.620000005f, 0.200000003f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {14.0f, 10.0f, 0.939999998f, 0.800000012f},
        "Projected cookie spotlight"
    },
    HardcodedDefaultEntry{
        244u, "Twin reflecting pool submerged bed",
        {13.8538303f, -0.299999952f, 16.803587f},
        {0.0f, -1.57686007f, 0.0f},
        {11.1000004f, 0.439999998f, 6.79999971f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool duplicate"
    },
    HardcodedDefaultEntry{
        245u, "Twin reflecting pool north coping",
        {17.3696518f, 0.0799999982f, 16.7999992f},
        {0.0f, -1.57686007f, 0.0f},
        {11.8000002f, 0.379999995f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool duplicate"
    },
    HardcodedDefaultEntry{
        246u, "Twin reflecting pool south coping",
        {10.3039036f, 0.0799999982f, 16.7820568f},
        {0.0f, -1.57686007f, 0.0f},
        {11.8000002f, 0.379999995f, 0.419999987f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool duplicate"
    },
    HardcodedDefaultEntry{
        247u, "Twin reflecting pool west coping",
        {13.8883915f, 0.0799999982f, 11.1037064f},
        {0.0f, -1.57686007f, 0.0f},
        {0.419999987f, 0.379999995f, 6.69999981f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool duplicate"
    },
    HardcodedDefaultEntry{
        248u, "Twin reflecting pool east coping",
        {13.8192616f, 0.0799999982f, 22.5034752f},
        {0.0f, -1.57686007f, 0.0f},
        {0.419999987f, 0.379999995f, 6.69999981f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool duplicate"
    },
    HardcodedDefaultEntry{
        249u, "Twin pool fountain plinth",
        {13.8500004f, 0.219999999f, 16.7999992f},
        {0.0f, -1.57686007f, 0.0f},
        {0.850000024f, 0.5f, 0.850000024f},
        {1.0f, 1.0f, 1.0f},
        "Cylinder", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool duplicate"
    },
    HardcodedDefaultEntry{
        250u, "Twin pool brushed metal sculpture",
        {13.8538303f, 1.45000005f, 16.803587f},
        {0.0f, -1.57686007f, 0.0f},
        {1.75f, 1.75f, 1.75f},
        {1.0f, 1.0f, 1.0f},
        "Torus", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Architectural pool duplicate"
    },
    HardcodedDefaultEntry{
        251u, "Twin pool rock cluster A",
        {19.2068157f, -1.34045446f, 4.4000001f},
        {0.0f, -0.383972466f, 0.0f},
        {1.20000005f, 1.20000005f, 1.20000005f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Twin pool rocks"
    },
    HardcodedDefaultEntry{
        252u, "Twin pool rock cluster B",
        {18.761364f, -1.39181912f, 5.30000019f},
        {0.0f, 0.593412042f, 0.0f},
        {0.920000017f, 0.920000017f, 0.920000017f},
        {1.0f, 1.0f, 1.0f},
        "Rock cluster", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Twin pool rocks"
    },
    HardcodedDefaultEntry{
        253u, "[Effect] Twin bordered architectural reflecting pool",
        {13.8500004f, 0.0199999958f, 16.7999992f},
        {0.0f, -1.57686007f, 0.0f},
        {5.44999981f, 1.0f, 3.1500001f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {0.00999999978f, 1.0f, 0.0599999987f, 1.0f},
        "Architectural pool duplicate"
    },
    HardcodedDefaultEntry{
        254u, "[Effect] Twin pool light-mote emitter",
        {13.8538303f, 0.180000007f, 16.803587f},
        {0.0f, -1.57686007f, 0.0f},
        {1.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {1.0f, 1.0f, 0.0f, 0.0f},
        "Architectural pool duplicate"
    },
    HardcodedDefaultEntry{
        255u, "[Effect] Twin pool mist emitter",
        {13.8538303f, 0.120000005f, 16.7999992f},
        {0.0f, -1.57686007f, 0.0f},
        {1.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {1.0f, 1.0f, 0.0f, 0.0f},
        "Architectural pool duplicate"
    },
    HardcodedDefaultEntry{
        256u, "Instanced crate 1",
        {16.9500008f, 0.620000005f, -8.64999962f},
        {0.0f, 0.0f, 0.0f},
        {0.720000029f, 0.720000029f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Crate", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Instanced crate draw"
    },
    HardcodedDefaultEntry{
        257u, "Instanced crate 2",
        {18.0499992f, 0.620000005f, -8.64999962f},
        {0.0f, 0.370000005f, 0.0f},
        {0.720000029f, 0.720000029f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Crate", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Instanced crate draw"
    },
    HardcodedDefaultEntry{
        258u, "Instanced crate 3",
        {19.1499996f, 0.620000005f, -8.64999962f},
        {0.0f, 0.74000001f, 0.0f},
        {0.720000029f, 0.720000029f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Crate", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Instanced crate draw"
    },
    HardcodedDefaultEntry{
        259u, "Instanced crate 4",
        {20.25f, 0.620000005f, -8.64999962f},
        {0.0f, 1.11000001f, 0.0f},
        {0.720000029f, 0.720000029f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Crate", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Instanced crate draw"
    },
    HardcodedDefaultEntry{
        260u, "Instanced crate 5",
        {16.9500008f, 0.620000005f, -9.77000046f},
        {0.0f, 1.48000002f, 0.0f},
        {0.720000029f, 0.720000029f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Crate", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Instanced crate draw"
    },
    HardcodedDefaultEntry{
        261u, "Instanced crate 6",
        {18.0499992f, 0.620000005f, -9.77000046f},
        {0.0f, 1.85000002f, 0.0f},
        {0.720000029f, 0.720000029f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Crate", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Instanced crate draw"
    },
    HardcodedDefaultEntry{
        262u, "Instanced crate 7",
        {19.1499996f, 0.620000005f, -9.77000046f},
        {0.0f, 2.22000003f, 0.0f},
        {0.720000029f, 0.720000029f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Crate", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Instanced crate draw"
    },
    HardcodedDefaultEntry{
        263u, "Instanced crate 8",
        {20.25f, 0.620000005f, -9.77000046f},
        {0.0f, 2.58999991f, 0.0f},
        {0.720000029f, 0.720000029f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Crate", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Instanced crate draw"
    },
    HardcodedDefaultEntry{
        264u, "Instanced crate 9",
        {16.9500008f, 0.620000005f, -10.8900003f},
        {0.0f, 2.96000004f, 0.0f},
        {0.720000029f, 0.720000029f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Crate", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Instanced crate draw"
    },
    HardcodedDefaultEntry{
        265u, "Instanced crate 10",
        {18.0499992f, 0.620000005f, -10.8900003f},
        {0.0f, 3.32999992f, 0.0f},
        {0.720000029f, 0.720000029f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Crate", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Instanced crate draw"
    },
    HardcodedDefaultEntry{
        266u, "Instanced crate 11",
        {19.1499996f, 0.620000005f, -10.8900003f},
        {0.0f, 3.70000005f, 0.0f},
        {0.720000029f, 0.720000029f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Crate", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Instanced crate draw"
    },
    HardcodedDefaultEntry{
        267u, "Instanced crate 12",
        {20.25f, 0.620000005f, -10.8900003f},
        {0.0f, 4.07000017f, 0.0f},
        {0.720000029f, 0.720000029f, 0.720000029f},
        {1.0f, 1.0f, 1.0f},
        "Crate", true, false,
        {0.0f, 0.0f, 0.0f, 0.0f},
        "Instanced crate draw"
    },
    HardcodedDefaultEntry{
        268u, "Main terrain",
        {0.0f, -0.82f, -3.0f},
        {0.0f, 0.0f, 0.0f},
        {32.0f, 1.0f, 32.0f},
        {1.0f, 1.0f, 1.0f},
        "Cube", true, false,
        {3.6f, 0.0f, 0.0f, 0.0f},
        "Terrain"
    },
